#ifndef H_UtopiaOS_project_config
#define H_UtopiaOS_project_config

#define UTOPIAOS_VERSION_MAJOR @UtopiaOS_VERSION_MAJOR@
#define UTOPIAOS_VERSION_MINOR @UtopiaOS_VERSION_MINOR@
#define UTOPIAOS_VERSION_PATCH @UtopiaOS_VERSION_PATCH@
#define UTOPIAOS_VERSION_TWEAK @UtopiaOS_VERSION_TWEAK@

#define UTOPIAOS_HOSTED @UTOPIAOS_HOSTED_ASNUMBER@

#endif
